#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include "htmlprep.h"

namespace nb = nanobind;

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// <litgen_glue_code>  // Autogenerated code below! Do not edit!

// </litgen_glue_code> // Autogenerated code end
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  AUTOGENERATED CODE END !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

#include "smart/olx_istring.h"
#include <string>

namespace nb = nanobind;
using namespace nb::literals;

std::string PreprocessHtml(const std::string& html)
{
    const olxstr s(html);
    THtmlPreprocessor htmlp;
    htmlp.Preprocess(s);
    const olxch* data = s.raw_str();
    const size_t length = s.Length();
    return {data, data + length};
}


NB_MODULE(_olexpy, m)
{
    m.def("PreprocessHtml", nb::overload_cast<const std::string &>(&PreprocessHtml), "html"_a,
        "Preprocess html file");
}
