/******************************************************************************
* Copyright (c) 2004-2011 O. Dolomanov, OlexSys                               *
*                                                                             *
* This file is part of the OlexSys Development Framework.                     *
*                                                                             *
* This source file is distributed under the terms of the licence located in   *
* the root folder.                                                            *
******************************************************************************/

#include "fastsymm.h"

const olxstr FastSG_A112::fullName("A 1 1 2");
const olxstr FastSG_A112::hallSymbol("A 2");
const olxstr FastSG_A112_a::fullName("A 1 1 2/a");
const olxstr FastSG_A112_a::hallSymbol("-A 2a");
const olxstr FastSG_A112_m::fullName("A 1 1 2/m");
const olxstr FastSG_A112_m::hallSymbol("-A 2");
const olxstr FastSG_A112_n::fullName("A 1 1 2/n");
const olxstr FastSG_A112_n::hallSymbol("-A 2ac");
const olxstr FastSG_A11a::fullName("A 1 1 a");
const olxstr FastSG_A11a::hallSymbol("A -2a");
const olxstr FastSG_A11m::fullName("A 1 1 m");
const olxstr FastSG_A11m::hallSymbol("A -2");
const olxstr FastSG_A11n::fullName("A 1 1 n");
const olxstr FastSG_A11n::hallSymbol("A -2ac");
const olxstr FastSG_A2::fullName("A 1 2 1");
const olxstr FastSG_A2::hallSymbol("A 2y");
const olxstr FastSG_A2_a::fullName("A 1 2/a 1");
const olxstr FastSG_A2_a::hallSymbol("-A 2ya");
const olxstr FastSG_A2_m::fullName("A 1 2/m 1");
const olxstr FastSG_A2_m::hallSymbol("-A 2y");
const olxstr FastSG_A2_n::fullName("A 1 2/n 1");
const olxstr FastSG_A2_n::hallSymbol("-A 2yac");
const olxstr FastSG_A2122::fullName("A 21 2 2");
const olxstr FastSG_A2122::hallSymbol("A 2a 2a");
const olxstr FastSG_A21am::fullName("A 21 a m");
const olxstr FastSG_A21am::hallSymbol("A -2 2a");
const olxstr FastSG_A21ma::fullName("A 21 m a");
const olxstr FastSG_A21ma::hallSymbol("A -2a 2a");
const olxstr FastSG_A222::fullName("A 2 2 2");
const olxstr FastSG_A222::hallSymbol("A 2 2");
const olxstr FastSG_A2aa::fullName("A 2 a a");
const olxstr FastSG_A2aa::hallSymbol("A -2a 2");
const olxstr FastSG_A2mm::fullName("A 2 m m");
const olxstr FastSG_A2mm::hallSymbol("A -2 2");
const olxstr FastSG_Aa::fullName("A 1 a 1");
const olxstr FastSG_Aa::hallSymbol("A -2ya");
const olxstr FastSG_Aba2::fullName("A b a 2");
const olxstr FastSG_Aba2::hallSymbol("A 2 -2ac");
const olxstr FastSG_Abaa::fullName("A b a a");
const olxstr FastSG_Abaa::hallSymbol("-A 2a 2c");
const olxstr FastSG_Abm2::fullName("A b m 2");
const olxstr FastSG_Abm2::hallSymbol("A 2 -2c");
const olxstr FastSG_Abma::fullName("A b m a");
const olxstr FastSG_Abma::hallSymbol("-A 2ac 2ac");
const olxstr FastSG_Abmm::fullName("A b m m");
const olxstr FastSG_Abmm::hallSymbol("-A 2c 2c");
const olxstr FastSG_Ac2a::fullName("A c 2 a");
const olxstr FastSG_Ac2a::hallSymbol("A -2ac -2ac");
const olxstr FastSG_Ac2m::fullName("A c 2 m");
const olxstr FastSG_Ac2m::hallSymbol("A -2c -2c");
const olxstr FastSG_Acaa::fullName("A c a a");
const olxstr FastSG_Acaa::hallSymbol("-A 2ac 2c");
const olxstr FastSG_Acam::fullName("A c a m");
const olxstr FastSG_Acam::hallSymbol("-A 2 2ac");
const olxstr FastSG_Acmm::fullName("A c m m");
const olxstr FastSG_Acmm::hallSymbol("-A 2 2c");
const olxstr FastSG_Am::fullName("A 1 m 1");
const olxstr FastSG_Am::hallSymbol("A -2y");
const olxstr FastSG_Am2a::fullName("A m 2 a");
const olxstr FastSG_Am2a::hallSymbol("A -2a -2a");
const olxstr FastSG_Am2m::fullName("A m 2 m");
const olxstr FastSG_Am2m::hallSymbol("A -2 -2");
const olxstr FastSG_Ama2::fullName("A m a 2");
const olxstr FastSG_Ama2::hallSymbol("A 2 -2a");
const olxstr FastSG_Amaa::fullName("A m a a");
const olxstr FastSG_Amaa::hallSymbol("-A 2a 2");
const olxstr FastSG_Amam::fullName("A m a m");
const olxstr FastSG_Amam::hallSymbol("-A 2 2a");
const olxstr FastSG_Amm2::fullName("A m m 2");
const olxstr FastSG_Amm2::hallSymbol("A 2 -2");
const olxstr FastSG_Amma::fullName("A m m a");
const olxstr FastSG_Amma::hallSymbol("-A 2a 2a");
const olxstr FastSG_Ammm::fullName("A m m m");
const olxstr FastSG_Ammm::hallSymbol("-A 2 2");
const olxstr FastSG_An::fullName("A 1 n 1");
const olxstr FastSG_An::hallSymbol("A -2yac");
const olxstr FastSG_B112::fullName("B 1 1 2");
const olxstr FastSG_B112::hallSymbol("B 2");
const olxstr FastSG_B112_b::fullName("B 1 1 2/b");
const olxstr FastSG_B112_b::hallSymbol("-B 2b");
const olxstr FastSG_B112_m::fullName("B 1 1 2/m");
const olxstr FastSG_B112_m::hallSymbol("-B 2");
const olxstr FastSG_B112_n::fullName("B 1 1 2/n");
const olxstr FastSG_B112_n::hallSymbol("-B 2bc");
const olxstr FastSG_B11b::fullName("B 1 1 b");
const olxstr FastSG_B11b::hallSymbol("B -2b");
const olxstr FastSG_B11m::fullName("B 1 1 m");
const olxstr FastSG_B11m::hallSymbol("B -2");
const olxstr FastSG_B11n::fullName("B 1 1 n");
const olxstr FastSG_B11n::hallSymbol("B -2bc");
const olxstr FastSG_B2_b11::fullName("B 2/b 1 1");
const olxstr FastSG_B2_b11::hallSymbol("-B 2xb");
const olxstr FastSG_B2_m11::fullName("B 2/m 1 1");
const olxstr FastSG_B2_m11::hallSymbol("-B 2x");
const olxstr FastSG_B2_n11::fullName("B 2/n 1 1");
const olxstr FastSG_B2_n11::hallSymbol("-B 2xbc");
const olxstr FastSG_B211::fullName("B 2 1 1");
const olxstr FastSG_B211::hallSymbol("B 2x");
const olxstr FastSG_B2212::fullName("B 2 21 2");
const olxstr FastSG_B2212::hallSymbol("B 2 2b");
const olxstr FastSG_B222::fullName("B 2 2 2");
const olxstr FastSG_B222::hallSymbol("B 2 2");
const olxstr FastSG_B2cb::fullName("B 2 c b");
const olxstr FastSG_B2cb::hallSymbol("B -2bc 2");
const olxstr FastSG_B2cm::fullName("B 2 c m");
const olxstr FastSG_B2cm::hallSymbol("B -2c 2");
const olxstr FastSG_B2mb::fullName("B 2 m b");
const olxstr FastSG_B2mb::hallSymbol("B -2b 2");
const olxstr FastSG_B2mm::fullName("B 2 m m");
const olxstr FastSG_B2mm::hallSymbol("B -2 2");
const olxstr FastSG_Bb11::fullName("B b 1 1");
const olxstr FastSG_Bb11::hallSymbol("B -2xb");
const olxstr FastSG_Bb21m::fullName("B b 21 m");
const olxstr FastSG_Bb21m::hallSymbol("B -2 -2b");
const olxstr FastSG_Bb2b::fullName("B b 2 b");
const olxstr FastSG_Bb2b::hallSymbol("B -2b -2b");
const olxstr FastSG_Bba2::fullName("B b a 2");
const olxstr FastSG_Bba2::hallSymbol("B 2 -2bc");
const olxstr FastSG_Bbab::fullName("B b a b");
const olxstr FastSG_Bbab::hallSymbol("-B 2b 2bc");
const olxstr FastSG_Bbcb::fullName("B b c b");
const olxstr FastSG_Bbcb::hallSymbol("-B 2bc 2b");
const olxstr FastSG_Bbcm::fullName("B b c m");
const olxstr FastSG_Bbcm::hallSymbol("-B 2 2bc");
const olxstr FastSG_Bbm2::fullName("B b m 2");
const olxstr FastSG_Bbm2::hallSymbol("B 2 -2b");
const olxstr FastSG_Bbmb::fullName("B b m b");
const olxstr FastSG_Bbmb::hallSymbol("-B 2b 2b");
const olxstr FastSG_Bbmm::fullName("B b m m");
const olxstr FastSG_Bbmm::hallSymbol("-B 2 2b");
const olxstr FastSG_Bm11::fullName("B m 1 1");
const olxstr FastSG_Bm11::hallSymbol("B -2x");
const olxstr FastSG_Bm21b::fullName("B m 21 b");
const olxstr FastSG_Bm21b::hallSymbol("B -2b -2");
const olxstr FastSG_Bm2m::fullName("B m 2 m");
const olxstr FastSG_Bm2m::hallSymbol("B -2 -2");
const olxstr FastSG_Bma2::fullName("B m a 2");
const olxstr FastSG_Bma2::hallSymbol("B 2 -2c");
const olxstr FastSG_Bmab::fullName("B m a b");
const olxstr FastSG_Bmab::hallSymbol("-B 2bc 2");
const olxstr FastSG_Bmam::fullName("B m a m");
const olxstr FastSG_Bmam::hallSymbol("-B 2c 2");
const olxstr FastSG_Bmcm::fullName("B m c m");
const olxstr FastSG_Bmcm::hallSymbol("-B 2 2c");
const olxstr FastSG_Bmm2::fullName("B m m 2");
const olxstr FastSG_Bmm2::hallSymbol("B 2 -2");
const olxstr FastSG_Bmmb::fullName("B m m b");
const olxstr FastSG_Bmmb::hallSymbol("-B 2b 2");
const olxstr FastSG_Bmmm::fullName("B m m m");
const olxstr FastSG_Bmmm::hallSymbol("-B 2 2");
const olxstr FastSG_Bn11::fullName("B n 1 1");
const olxstr FastSG_Bn11::hallSymbol("B -2xbc");
const olxstr FastSG_C1::fullName("C 1");
const olxstr FastSG_C1::hallSymbol("C 1");
const olxstr FastSG_C2::fullName("C 1 2 1");
const olxstr FastSG_C2::hallSymbol("C 2y");
const olxstr FastSG_C2_c::fullName("C 1 2/c 1");
const olxstr FastSG_C2_c::hallSymbol("-C 2yc");
const olxstr FastSG_C2_c11::fullName("C 2/c 1 1");
const olxstr FastSG_C2_c11::hallSymbol("-C 2xc");
const olxstr FastSG_C2_m::fullName("C 1 2/m 1");
const olxstr FastSG_C2_m::hallSymbol("-C 2y");
const olxstr FastSG_C2_m11::fullName("C 2/m 1 1");
const olxstr FastSG_C2_m11::hallSymbol("-C 2x");
const olxstr FastSG_C2_n::fullName("C 1 2/n 1");
const olxstr FastSG_C2_n::hallSymbol("-C 2ybc");
const olxstr FastSG_C2_n11::fullName("C 2/n 1 1");
const olxstr FastSG_C2_n11::hallSymbol("-C 2xbc");
const olxstr FastSG_C211::fullName("C 2 1 1");
const olxstr FastSG_C211::hallSymbol("C 2x");
const olxstr FastSG_C222::fullName("C 2 2 2");
const olxstr FastSG_C222::hallSymbol("C 2 2");
const olxstr FastSG_C2221::fullName("C 2 2 21");
const olxstr FastSG_C2221::hallSymbol("C 2c 2");
const olxstr FastSG_C2cb::fullName("C 2 c b");
const olxstr FastSG_C2cb::hallSymbol("C -2bc 2");
const olxstr FastSG_C2cm::fullName("C 2 c m");
const olxstr FastSG_C2cm::hallSymbol("C -2c 2");
const olxstr FastSG_C2mb::fullName("C 2 m b");
const olxstr FastSG_C2mb::hallSymbol("C -2b 2");
const olxstr FastSG_C2mm::fullName("C 2 m m");
const olxstr FastSG_C2mm::hallSymbol("C -2 2");
const olxstr FastSG_Cc::fullName("C 1 c 1");
const olxstr FastSG_Cc::hallSymbol("C -2yc");
const olxstr FastSG_Cc11::fullName("C c 1 1");
const olxstr FastSG_Cc11::hallSymbol("C -2xc");
const olxstr FastSG_Cc2a::fullName("C c 2 a");
const olxstr FastSG_Cc2a::hallSymbol("C -2bc -2bc");
const olxstr FastSG_Cc2m::fullName("C c 2 m");
const olxstr FastSG_Cc2m::hallSymbol("C -2c -2c");
const olxstr FastSG_Ccc2::fullName("C c c 2");
const olxstr FastSG_Ccc2::hallSymbol("C 2 -2c");
const olxstr FastSG_Ccca::fullName("C c c a");
const olxstr FastSG_Ccca::hallSymbol("-C 2b 2bc");
const olxstr FastSG_Cccb::fullName("C c c b");
const olxstr FastSG_Cccb::hallSymbol("-C 2b 2c");
const olxstr FastSG_Cccm::fullName("C c c m");
const olxstr FastSG_Cccm::hallSymbol("-C 2 2c");
const olxstr FastSG_Ccm21::fullName("C c m 21");
const olxstr FastSG_Ccm21::hallSymbol("C 2c -2c");
const olxstr FastSG_Ccmb::fullName("C c m b");
const olxstr FastSG_Ccmb::hallSymbol("-C 2bc 2bc");
const olxstr FastSG_Ccmm::fullName("C c m m");
const olxstr FastSG_Ccmm::hallSymbol("-C 2c 2c");
const olxstr FastSG_Cm::fullName("C 1 m 1");
const olxstr FastSG_Cm::hallSymbol("C -2y");
const olxstr FastSG_Cm11::fullName("C m 1 1");
const olxstr FastSG_Cm11::hallSymbol("C -2x");
const olxstr FastSG_Cm2a::fullName("C m 2 a");
const olxstr FastSG_Cm2a::hallSymbol("C -2b -2b");
const olxstr FastSG_Cm2m::fullName("C m 2 m");
const olxstr FastSG_Cm2m::hallSymbol("C -2 -2");
const olxstr FastSG_Cmc21::fullName("C m c 21");
const olxstr FastSG_Cmc21::hallSymbol("C 2c -2");
const olxstr FastSG_Cmca::fullName("C m c a");
const olxstr FastSG_Cmca::hallSymbol("-C 2bc 2");
const olxstr FastSG_Cmcm::fullName("C m c m");
const olxstr FastSG_Cmcm::hallSymbol("-C 2c 2");
const olxstr FastSG_Cmm2::fullName("C m m 2");
const olxstr FastSG_Cmm2::hallSymbol("C 2 -2");
const olxstr FastSG_Cmma::fullName("C m m a");
const olxstr FastSG_Cmma::hallSymbol("-C 2b 2");
const olxstr FastSG_Cmmb::fullName("C m m b");
const olxstr FastSG_Cmmb::hallSymbol("-C 2b 2b");
const olxstr FastSG_Cmmm::fullName("C m m m");
const olxstr FastSG_Cmmm::hallSymbol("-C 2 2");
const olxstr FastSG_Cn::fullName("C 1 n 1");
const olxstr FastSG_Cn::hallSymbol("C -2ybc");
const olxstr FastSG_Cn11::fullName("C n 1 1");
const olxstr FastSG_Cn11::hallSymbol("C -2xbc");
const olxstr FastSG_F_43c::fullName("F -4 3 c");
const olxstr FastSG_F_43c::hallSymbol("F -4c 2 3");
const olxstr FastSG_F_43m::fullName("F -4 3 m");
const olxstr FastSG_F_43m::hallSymbol("F -4 2 3");
const olxstr FastSG_F222::fullName("F 2 2 2");
const olxstr FastSG_F222::hallSymbol("F 2 2");
const olxstr FastSG_F23::fullName("F 2 3 F");
const olxstr FastSG_F23::hallSymbol("F 2 2 3");
const olxstr FastSG_F2dd::fullName("F 2 d d");
const olxstr FastSG_F2dd::hallSymbol("F -2d 2");
const olxstr FastSG_F2mm::fullName("F 2 m m");
const olxstr FastSG_F2mm::hallSymbol("F -2 2");
const olxstr FastSG_F4132::fullName("F 41 3 2");
const olxstr FastSG_F4132::hallSymbol("F 4d 2 3");
const olxstr FastSG_F432::fullName("F 4 3 2");
const olxstr FastSG_F432::hallSymbol("F 4 2 3");
const olxstr FastSG_Fd_3::fullName("F d -3");
const olxstr FastSG_Fd_3::hallSymbol("-F 2uv 2vw 3");
const olxstr FastSG_Fd_3c::fullName("F d -3 c");
const olxstr FastSG_Fd_3c::hallSymbol("-F 4cvw 2vw 3");
const olxstr FastSG_Fd_3m::fullName("F d -3 m");
const olxstr FastSG_Fd_3m::hallSymbol("-F 4vw 2vw 3");
const olxstr FastSG_Fd2d::fullName("F d 2 d");
const olxstr FastSG_Fd2d::hallSymbol("F -2d -2d");
const olxstr FastSG_Fdd2::fullName("F d d 2");
const olxstr FastSG_Fdd2::hallSymbol("F 2 -2d");
const olxstr FastSG_Fddd::fullName("F d d d");
const olxstr FastSG_Fddd::hallSymbol("-F 2uv 2vw");
const olxstr FastSG_Fm_3::fullName("F m -3");
const olxstr FastSG_Fm_3::hallSymbol("-F 2 2 3");
const olxstr FastSG_Fm_3c::fullName("F m -3 c");
const olxstr FastSG_Fm_3c::hallSymbol("-F 4c 2 3");
const olxstr FastSG_Fm_3m::fullName("F m -3 m");
const olxstr FastSG_Fm_3m::hallSymbol("-F 4 2 3");
const olxstr FastSG_Fm2m::fullName("F m 2 m");
const olxstr FastSG_Fm2m::hallSymbol("F -2 -2");
const olxstr FastSG_Fmm2::fullName("F m m 2");
const olxstr FastSG_Fmm2::hallSymbol("F 2 -2");
const olxstr FastSG_Fmmm::fullName("F m m m");
const olxstr FastSG_Fmmm::hallSymbol("-F 2 2");
const olxstr FastSG_Fx::fullName("");
const olxstr FastSG_Fx::hallSymbol("F 1");
const olxstr FastSG_I_4::fullName("I -4");
const olxstr FastSG_I_4::hallSymbol("I -4");
const olxstr FastSG_I_42d::fullName("I -4 2 d");
const olxstr FastSG_I_42d::hallSymbol("I -4 2bw");
const olxstr FastSG_I_42m::fullName("I -4 2 m");
const olxstr FastSG_I_42m::hallSymbol("I -4 2");
const olxstr FastSG_I_43d::fullName("I -4 3 d");
const olxstr FastSG_I_43d::hallSymbol("I -4bd 2c 3");
const olxstr FastSG_I_43m::fullName("I -4 3 m");
const olxstr FastSG_I_43m::hallSymbol("I -4 2 3");
const olxstr FastSG_I_4c2::fullName("I -4 c 2");
const olxstr FastSG_I_4c2::hallSymbol("I -4 -2c");
const olxstr FastSG_I_4m2::fullName("I -4 m 2");
const olxstr FastSG_I_4m2::hallSymbol("I -4 -2");
const olxstr FastSG_I112::fullName("I 1 1 2");
const olxstr FastSG_I112::hallSymbol("I 2");
const olxstr FastSG_I112_a::fullName("I 1 1 2/a");
const olxstr FastSG_I112_a::hallSymbol("-I 2a");
const olxstr FastSG_I112_b::fullName("I 1 1 2/b");
const olxstr FastSG_I112_b::hallSymbol("-I 2b");
const olxstr FastSG_I112_m::fullName("I 1 1 2/m");
const olxstr FastSG_I112_m::hallSymbol("-I 2");
const olxstr FastSG_I11a::fullName("I 1 1 a");
const olxstr FastSG_I11a::hallSymbol("I -2a");
const olxstr FastSG_I11b::fullName("I 1 1 b");
const olxstr FastSG_I11b::hallSymbol("I -2b");
const olxstr FastSG_I11m::fullName("I 1 1 m");
const olxstr FastSG_I11m::hallSymbol("I -2");
const olxstr FastSG_I2::fullName("I 1 2 1");
const olxstr FastSG_I2::hallSymbol("I 2y");
const olxstr FastSG_I2_a::fullName("I 1 2/a 1");
const olxstr FastSG_I2_a::hallSymbol("-I 2ya");
const olxstr FastSG_I2_b11::fullName("I 2/b 1 1");
const olxstr FastSG_I2_b11::hallSymbol("-I 2xb");
const olxstr FastSG_I2_c::fullName("I 1 2/c 1");
const olxstr FastSG_I2_c::hallSymbol("-I 2yc");
const olxstr FastSG_I2_c11::fullName("I 2/c 1 1");
const olxstr FastSG_I2_c11::hallSymbol("-I 2xc");
const olxstr FastSG_I2_m::fullName("I 1 2/m 1");
const olxstr FastSG_I2_m::hallSymbol("-I 2y");
const olxstr FastSG_I2_m11::fullName("I 2/m 1 1");
const olxstr FastSG_I2_m11::hallSymbol("-I 2x");
const olxstr FastSG_I211::fullName("I 2 1 1");
const olxstr FastSG_I211::hallSymbol("I 2x");
const olxstr FastSG_I212121::fullName("I 21 21 21");
const olxstr FastSG_I212121::hallSymbol("I 2b 2c");
const olxstr FastSG_I213::fullName("I 21 3 I");
const olxstr FastSG_I213::hallSymbol("I 2b 2c 3");
const olxstr FastSG_I222::fullName("I 2 2 2");
const olxstr FastSG_I222::hallSymbol("I 2 2");
const olxstr FastSG_I23::fullName("I 2 3 I");
const olxstr FastSG_I23::hallSymbol("I 2 2 3");
const olxstr FastSG_I2cb::fullName("I 2 c b");
const olxstr FastSG_I2cb::hallSymbol("I -2a 2");
const olxstr FastSG_I2cm::fullName("I 2 c m");
const olxstr FastSG_I2cm::hallSymbol("I -2c 2");
const olxstr FastSG_I2mb::fullName("I 2 m b");
const olxstr FastSG_I2mb::hallSymbol("I -2b 2");
const olxstr FastSG_I2mm::fullName("I 2 m m");
const olxstr FastSG_I2mm::hallSymbol("I -2 2");
const olxstr FastSG_I4::fullName("I 4");
const olxstr FastSG_I4::hallSymbol("I 4");
const olxstr FastSG_I4_m::fullName("I 4/m");
const olxstr FastSG_I4_m::hallSymbol("-I 4");
const olxstr FastSG_I4_mcm::fullName("I 4/m c m");
const olxstr FastSG_I4_mcm::hallSymbol("-I 4 2c");
const olxstr FastSG_I4_mmm::fullName("I 4/m m m");
const olxstr FastSG_I4_mmm::hallSymbol("-I 4 2");
const olxstr FastSG_I41::fullName("I 41");
const olxstr FastSG_I41::hallSymbol("I 4bw");
const olxstr FastSG_I41_a::fullName("I 41/a");
const olxstr FastSG_I41_a::hallSymbol("-I 4ad");
const olxstr FastSG_I41_acd::fullName("I 41/a c d");
const olxstr FastSG_I41_acd::hallSymbol("-I 4bd 2c");
const olxstr FastSG_I41_amd::fullName("I 41/a m d");
const olxstr FastSG_I41_amd::hallSymbol("-I 4bd 2");
const olxstr FastSG_I4122::fullName("I 41 2 2");
const olxstr FastSG_I4122::hallSymbol("I 4bw 2bw");
const olxstr FastSG_I4132::fullName("I 41 3 2");
const olxstr FastSG_I4132::hallSymbol("I 4bd 2c 3");
const olxstr FastSG_I41cd::fullName("I 41 c d");
const olxstr FastSG_I41cd::hallSymbol("I 4bw -2c");
const olxstr FastSG_I41md::fullName("I 41 m d");
const olxstr FastSG_I41md::hallSymbol("I 4bw -2");
const olxstr FastSG_I422::fullName("I 4 2 2");
const olxstr FastSG_I422::hallSymbol("I 4 2");
const olxstr FastSG_I432::fullName("I 4 3 2");
const olxstr FastSG_I432::hallSymbol("I 4 2 3");
const olxstr FastSG_I4cm::fullName("I 4 c m");
const olxstr FastSG_I4cm::hallSymbol("I 4 -2c");
const olxstr FastSG_I4mm::fullName("I 4 m m");
const olxstr FastSG_I4mm::hallSymbol("I 4 -2");
const olxstr FastSG_Ia::fullName("I 1 a 1");
const olxstr FastSG_Ia::hallSymbol("I -2ya");
const olxstr FastSG_Ia_3::fullName("I a -3");
const olxstr FastSG_Ia_3::hallSymbol("-I 2b 2c 3");
const olxstr FastSG_Ia_3d::fullName("I a -3 d");
const olxstr FastSG_Ia_3d::hallSymbol("-I 4bd 2c 3");
const olxstr FastSG_Ib11::fullName("I b 1 1");
const olxstr FastSG_Ib11::hallSymbol("I -2xb");
const olxstr FastSG_Iba2::fullName("I b a 2");
const olxstr FastSG_Iba2::hallSymbol("I 2 -2c");
const olxstr FastSG_Ibam::fullName("I b a m");
const olxstr FastSG_Ibam::hallSymbol("-I 2 2c");
const olxstr FastSG_Ibca::fullName("I b c a");
const olxstr FastSG_Ibca::hallSymbol("-I 2b 2c");
const olxstr FastSG_Ibm2::fullName("I b m 2");
const olxstr FastSG_Ibm2::hallSymbol("I 2 -2b");
const olxstr FastSG_Ibmm::fullName("I b m m");
const olxstr FastSG_Ibmm::hallSymbol("-I 2c 2c");
const olxstr FastSG_Ic::fullName("I 1 c 1");
const olxstr FastSG_Ic::hallSymbol("I -2yc");
const olxstr FastSG_Ic11::fullName("I c 1 1");
const olxstr FastSG_Ic11::hallSymbol("I -2xc");
const olxstr FastSG_Ic2a::fullName("I c 2 a");
const olxstr FastSG_Ic2a::hallSymbol("I -2b -2b");
const olxstr FastSG_Ic2m::fullName("I c 2 m");
const olxstr FastSG_Ic2m::hallSymbol("I -2c -2c");
const olxstr FastSG_Icab::fullName("I c a b");
const olxstr FastSG_Icab::hallSymbol("-I 2a 2b");
const olxstr FastSG_Icma::fullName("I c m a");
const olxstr FastSG_Icma::hallSymbol("-I 2b 2b");
const olxstr FastSG_Icmm::fullName("I c m m");
const olxstr FastSG_Icmm::hallSymbol("-I 2 2b");
const olxstr FastSG_Im::fullName("I 1 m 1");
const olxstr FastSG_Im::hallSymbol("I -2y");
const olxstr FastSG_Im_3::fullName("I m -3");
const olxstr FastSG_Im_3::hallSymbol("-I 2 2 3");
const olxstr FastSG_Im_3m::fullName("I m -3 m");
const olxstr FastSG_Im_3m::hallSymbol("-I 4 2 3");
const olxstr FastSG_Im11::fullName("I m 1 1");
const olxstr FastSG_Im11::hallSymbol("I -2x");
const olxstr FastSG_Im2a::fullName("I m 2 a");
const olxstr FastSG_Im2a::hallSymbol("I -2a -2a");
const olxstr FastSG_Im2m::fullName("I m 2 m");
const olxstr FastSG_Im2m::hallSymbol("I -2 -2");
const olxstr FastSG_Ima2::fullName("I m a 2");
const olxstr FastSG_Ima2::hallSymbol("I 2 -2a");
const olxstr FastSG_Imam::fullName("I m a m");
const olxstr FastSG_Imam::hallSymbol("-I 2c 2");
const olxstr FastSG_Imcb::fullName("I m c b");
const olxstr FastSG_Imcb::hallSymbol("-I 2a 2");
const olxstr FastSG_Imcm::fullName("I m c m");
const olxstr FastSG_Imcm::hallSymbol("-I 2 2a");
const olxstr FastSG_Imm2::fullName("I m m 2");
const olxstr FastSG_Imm2::hallSymbol("I 2 -2");
const olxstr FastSG_Imma::fullName("I m m a");
const olxstr FastSG_Imma::hallSymbol("-I 2b 2");
const olxstr FastSG_Immb::fullName("I m m b");
const olxstr FastSG_Immb::hallSymbol("-I 2a 2a");
const olxstr FastSG_Immm::fullName("I m m m");
const olxstr FastSG_Immm::hallSymbol("-I 2 2");
const olxstr FastSG_P_1::fullName("P -1");
const olxstr FastSG_P_1::hallSymbol("-P 1");
const olxstr FastSG_P_3::fullName("P -3");
const olxstr FastSG_P_3::hallSymbol("-P 3");
const olxstr FastSG_P_31c::fullName("P -3 1 c");
const olxstr FastSG_P_31c::hallSymbol("-P 3 2c");
const olxstr FastSG_P_31m::fullName("P -3 1 m");
const olxstr FastSG_P_31m::hallSymbol("-P 3 2");
const olxstr FastSG_P_3c1::fullName("P -3 c 1");
const olxstr FastSG_P_3c1::hallSymbol("-P 3 2\"c");
const olxstr FastSG_P_3m1::fullName("P -3 m 1");
const olxstr FastSG_P_3m1::hallSymbol("-P 3 2\"");
const olxstr FastSG_P_4::fullName("P -4");
const olxstr FastSG_P_4::hallSymbol("P -4");
const olxstr FastSG_P_421c::fullName("P -4 21 c");
const olxstr FastSG_P_421c::hallSymbol("P -4 2n");
const olxstr FastSG_P_421m::fullName("P -4 21 m");
const olxstr FastSG_P_421m::hallSymbol("P -4 2ab");
const olxstr FastSG_P_42c::fullName("P -4 2 c");
const olxstr FastSG_P_42c::hallSymbol("P -4 2c");
const olxstr FastSG_P_42m::fullName("P -4 2 m");
const olxstr FastSG_P_42m::hallSymbol("P -4 2");
const olxstr FastSG_P_43m::fullName("P -4 3 m");
const olxstr FastSG_P_43m::hallSymbol("P -4 2 3");
const olxstr FastSG_P_43n::fullName("P -4 3 n");
const olxstr FastSG_P_43n::hallSymbol("P -4n 2 3");
const olxstr FastSG_P_4b2::fullName("P -4 b 2");
const olxstr FastSG_P_4b2::hallSymbol("P -4 -2ab");
const olxstr FastSG_P_4c2::fullName("P -4 c 2");
const olxstr FastSG_P_4c2::hallSymbol("P -4 -2c");
const olxstr FastSG_P_4m2::fullName("P -4 m 2");
const olxstr FastSG_P_4m2::hallSymbol("P -4 -2");
const olxstr FastSG_P_4n2::fullName("P -4 n 2");
const olxstr FastSG_P_4n2::hallSymbol("P -4 -2n");
const olxstr FastSG_P_6::fullName("P -6");
const olxstr FastSG_P_6::hallSymbol("P -6");
const olxstr FastSG_P_62c::fullName("P -6 2 c");
const olxstr FastSG_P_62c::hallSymbol("P -6c -2c");
const olxstr FastSG_P_62m::fullName("P -6 2 m");
const olxstr FastSG_P_62m::hallSymbol("P -6 -2");
const olxstr FastSG_P_6c2::fullName("P -6 c 2");
const olxstr FastSG_P_6c2::hallSymbol("P -6c 2");
const olxstr FastSG_P_6m2::fullName("P -6 m 2");
const olxstr FastSG_P_6m2::hallSymbol("P -6 2");
const olxstr FastSG_P1::fullName("P 1");
const olxstr FastSG_P1::hallSymbol("P 1");
const olxstr FastSG_P112::fullName("P 1 1 2");
const olxstr FastSG_P112::hallSymbol("P 2");
const olxstr FastSG_P112_a::fullName("P 1 1 2/a");
const olxstr FastSG_P112_a::hallSymbol("-P 2a");
const olxstr FastSG_P112_b::fullName("P 1 1 2/b");
const olxstr FastSG_P112_b::hallSymbol("-P 2b");
const olxstr FastSG_P112_m::fullName("P 1 1 2/m");
const olxstr FastSG_P112_m::hallSymbol("-P 2");
const olxstr FastSG_P112_n::fullName("P 1 1 2/n");
const olxstr FastSG_P112_n::hallSymbol("-P 2ab");
const olxstr FastSG_P1121::fullName("P 1 1 21");
const olxstr FastSG_P1121::hallSymbol("P 2c");
const olxstr FastSG_P1121_a::fullName("P 1 1 21/a");
const olxstr FastSG_P1121_a::hallSymbol("-P 2ac");
const olxstr FastSG_P1121_b::fullName("P 1 1 21/b");
const olxstr FastSG_P1121_b::hallSymbol("-P 2bc");
const olxstr FastSG_P1121_m::fullName("P 1 1 21/m");
const olxstr FastSG_P1121_m::hallSymbol("-P 2c");
const olxstr FastSG_P1121_n::fullName("P 1 1 21/n");
const olxstr FastSG_P1121_n::hallSymbol("-P 2n");
const olxstr FastSG_P11a::fullName("P 1 1 a");
const olxstr FastSG_P11a::hallSymbol("P -2a");
const olxstr FastSG_P11b::fullName("P 1 1 b");
const olxstr FastSG_P11b::hallSymbol("P -2b");
const olxstr FastSG_P11m::fullName("P 1 1 m");
const olxstr FastSG_P11m::hallSymbol("P -2");
const olxstr FastSG_P11n::fullName("P 1 1 n");
const olxstr FastSG_P11n::hallSymbol("P -2ab");
const olxstr FastSG_P2::fullName("P 1 2 1");
const olxstr FastSG_P2::hallSymbol("P 2y");
const olxstr FastSG_P2_a::fullName("P 1 2/a 1");
const olxstr FastSG_P2_a::hallSymbol("-P 2ya");
const olxstr FastSG_P2_b11::fullName("P 2/b 1 1");
const olxstr FastSG_P2_b11::hallSymbol("-P 2xb");
const olxstr FastSG_P2_c::fullName("P 1 2/c 1");
const olxstr FastSG_P2_c::hallSymbol("-P 2yc");
const olxstr FastSG_P2_c11::fullName("P 2/c 1 1");
const olxstr FastSG_P2_c11::hallSymbol("-P 2xc");
const olxstr FastSG_P2_m::fullName("P 1 2/m 1");
const olxstr FastSG_P2_m::hallSymbol("-P 2y");
const olxstr FastSG_P2_m11::fullName("P 2/m 1 1");
const olxstr FastSG_P2_m11::hallSymbol("-P 2x");
const olxstr FastSG_P2_n::fullName("P 1 2/n 1");
const olxstr FastSG_P2_n::hallSymbol("-P 2yac");
const olxstr FastSG_P2_n11::fullName("P 2/n 1 1");
const olxstr FastSG_P2_n11::hallSymbol("-P 2xbc");
const olxstr FastSG_P21::fullName("P 1 21 1");
const olxstr FastSG_P21::hallSymbol("P 2yb");
const olxstr FastSG_P21_a::fullName("P 1 21/a 1");
const olxstr FastSG_P21_a::hallSymbol("-P 2yab");
const olxstr FastSG_P21_b11::fullName("P 21/b 1 1");
const olxstr FastSG_P21_b11::hallSymbol("-P 2xab");
const olxstr FastSG_P21_c::fullName("P 1 21/c 1");
const olxstr FastSG_P21_c::hallSymbol("-P 2ybc");
const olxstr FastSG_P21_c11::fullName("P 21/c 1 1");
const olxstr FastSG_P21_c11::hallSymbol("-P 2xac");
const olxstr FastSG_P21_m::fullName("P 1 21/m 1");
const olxstr FastSG_P21_m::hallSymbol("-P 2yb");
const olxstr FastSG_P21_m11::fullName("P 21/m 1 1");
const olxstr FastSG_P21_m11::hallSymbol("-P 2xa");
const olxstr FastSG_P21_n::fullName("P 1 21/n 1");
const olxstr FastSG_P21_n::hallSymbol("-P 2yn");
const olxstr FastSG_P21_n11::fullName("P 21/n 1 1");
const olxstr FastSG_P21_n11::hallSymbol("-P 2xn");
const olxstr FastSG_P211::fullName("P 2 1 1");
const olxstr FastSG_P211::hallSymbol("P 2x");
const olxstr FastSG_P2111::fullName("P 21 1 1");
const olxstr FastSG_P2111::hallSymbol("P 2xa");
const olxstr FastSG_P21212::fullName("P 21 21 2");
const olxstr FastSG_P21212::hallSymbol("P 2 2ab");
const olxstr FastSG_P212121::fullName("P 21 21 21");
const olxstr FastSG_P212121::hallSymbol("P 2ac 2ab");
const olxstr FastSG_P2122::fullName("P 21 2 2");
const olxstr FastSG_P2122::hallSymbol("P 2a 2a");
const olxstr FastSG_P21221::fullName("P 21 2 21");
const olxstr FastSG_P21221::hallSymbol("P 2ac 2ac");
const olxstr FastSG_P213::fullName("P 21 3 P");
const olxstr FastSG_P213::hallSymbol("P 2ac 2ab 3");
const olxstr FastSG_P21ab::fullName("P 21 a b");
const olxstr FastSG_P21ab::hallSymbol("P -2b 2a");
const olxstr FastSG_P21am::fullName("P 21 a m");
const olxstr FastSG_P21am::hallSymbol("P -2 2a");
const olxstr FastSG_P21ca::fullName("P 21 c a");
const olxstr FastSG_P21ca::hallSymbol("P -2ac 2a");
const olxstr FastSG_P21cn::fullName("P 21 c n");
const olxstr FastSG_P21cn::hallSymbol("P -2n 2a");
const olxstr FastSG_P21ma::fullName("P 21 m a");
const olxstr FastSG_P21ma::hallSymbol("P -2a 2a");
const olxstr FastSG_P21mn::fullName("P 21 m n");
const olxstr FastSG_P21mn::hallSymbol("P -2ab 2ab");
const olxstr FastSG_P21nb::fullName("P 21 n b");
const olxstr FastSG_P21nb::hallSymbol("P -2bc 2a");
const olxstr FastSG_P21nm::fullName("P 21 n m");
const olxstr FastSG_P21nm::hallSymbol("P -2 2ac");
const olxstr FastSG_P2212::fullName("P 2 21 2");
const olxstr FastSG_P2212::hallSymbol("P 2 2b");
const olxstr FastSG_P22121::fullName("P 2 21 21");
const olxstr FastSG_P22121::hallSymbol("P 2bc 2");
const olxstr FastSG_P222::fullName("P 2 2 2");
const olxstr FastSG_P222::hallSymbol("P 2 2");
const olxstr FastSG_P2221::fullName("P 2 2 21");
const olxstr FastSG_P2221::hallSymbol("P 2c 2");
const olxstr FastSG_P23::fullName("P 2 3 P");
const olxstr FastSG_P23::hallSymbol("P 2 2 3");
const olxstr FastSG_P2aa::fullName("P 2 a a");
const olxstr FastSG_P2aa::hallSymbol("P -2a 2");
const olxstr FastSG_P2an::fullName("P 2 a n");
const olxstr FastSG_P2an::hallSymbol("P -2ab 2");
const olxstr FastSG_P2cb::fullName("P 2 c b");
const olxstr FastSG_P2cb::hallSymbol("P -2bc 2");
const olxstr FastSG_P2cm::fullName("P 2 c m");
const olxstr FastSG_P2cm::hallSymbol("P -2c 2");
const olxstr FastSG_P2mb::fullName("P 2 m b");
const olxstr FastSG_P2mb::hallSymbol("P -2b 2");
const olxstr FastSG_P2mm::fullName("P 2 m m");
const olxstr FastSG_P2mm::hallSymbol("P -2 2");
const olxstr FastSG_P2na::fullName("P 2 n a");
const olxstr FastSG_P2na::hallSymbol("P -2ac 2");
const olxstr FastSG_P2nn::fullName("P 2 n n");
const olxstr FastSG_P2nn::hallSymbol("P -2n 2");
const olxstr FastSG_P3::fullName("P 3");
const olxstr FastSG_P3::hallSymbol("P 3");
const olxstr FastSG_P31::fullName("P 31");
const olxstr FastSG_P31::hallSymbol("P 31");
const olxstr FastSG_P3112::fullName("P 31 1 2");
const olxstr FastSG_P3112::hallSymbol("P 31 2");
const olxstr FastSG_P312::fullName("P 3 1 2");
const olxstr FastSG_P312::hallSymbol("P 3 2");
const olxstr FastSG_P3121::fullName("P 31 2 1");
const olxstr FastSG_P3121::hallSymbol("P 31 2\"");
const olxstr FastSG_P31c::fullName("P 3 1 c");
const olxstr FastSG_P31c::hallSymbol("P 3 -2c");
const olxstr FastSG_P31m::fullName("P 3 1 m");
const olxstr FastSG_P31m::hallSymbol("P 3 -2");
const olxstr FastSG_P32::fullName("P 32");
const olxstr FastSG_P32::hallSymbol("P 32");
const olxstr FastSG_P321::fullName("P 3 2 1");
const olxstr FastSG_P321::hallSymbol("P 3 2\"");
const olxstr FastSG_P3212::fullName("P 32 1 2");
const olxstr FastSG_P3212::hallSymbol("P 32 2");
const olxstr FastSG_P3221::fullName("P 32 2 1");
const olxstr FastSG_P3221::hallSymbol("P 32 2\"");
const olxstr FastSG_P3c1::fullName("P 3 c 1");
const olxstr FastSG_P3c1::hallSymbol("P 3 -2\"c");
const olxstr FastSG_P3m1::fullName("P 3 m 1");
const olxstr FastSG_P3m1::hallSymbol("P 3 -2\"");
const olxstr FastSG_P4::fullName("P 4");
const olxstr FastSG_P4::hallSymbol("P 4");
const olxstr FastSG_P4_m::fullName("P 4/m");
const olxstr FastSG_P4_m::hallSymbol("-P 4");
const olxstr FastSG_P4_mbm::fullName("P 4/m b m");
const olxstr FastSG_P4_mbm::hallSymbol("-P 4 2ab");
const olxstr FastSG_P4_mcc::fullName("P 4/m c c");
const olxstr FastSG_P4_mcc::hallSymbol("-P 4 2c");
const olxstr FastSG_P4_mmm::fullName("P 4/m m m");
const olxstr FastSG_P4_mmm::hallSymbol("-P 4 2");
const olxstr FastSG_P4_mnc::fullName("P 4/m n c");
const olxstr FastSG_P4_mnc::hallSymbol("-P 4 2n");
const olxstr FastSG_P4_n::fullName("P 4/n");
const olxstr FastSG_P4_n::hallSymbol("-P 4a");
const olxstr FastSG_P4_nbm::fullName("P 4/n b m");
const olxstr FastSG_P4_nbm::hallSymbol("-P 4a 2b");
const olxstr FastSG_P4_ncc::fullName("P 4/n c c");
const olxstr FastSG_P4_ncc::hallSymbol("-P 4a 2ac");
const olxstr FastSG_P4_nmm::fullName("P 4/n m m");
const olxstr FastSG_P4_nmm::hallSymbol("-P 4a 2a");
const olxstr FastSG_P4_nnc::fullName("P 4/n n c");
const olxstr FastSG_P4_nnc::hallSymbol("-P 4a 2bc");
const olxstr FastSG_P41::fullName("P 41");
const olxstr FastSG_P41::hallSymbol("P 41");
const olxstr FastSG_P41212::fullName("P 41 21 2");
const olxstr FastSG_P41212::hallSymbol("P 4abw 2nw");
const olxstr FastSG_P4122::fullName("P 41 2 2");
const olxstr FastSG_P4122::hallSymbol("P 41 2c");
const olxstr FastSG_P4132::fullName("P 41 3 2");
const olxstr FastSG_P4132::hallSymbol("P 4bd 2ab 3");
const olxstr FastSG_P42::fullName("P 42");
const olxstr FastSG_P42::hallSymbol("P 4c");
const olxstr FastSG_P42_m::fullName("P 42/m");
const olxstr FastSG_P42_m::hallSymbol("-P 4c");
const olxstr FastSG_P42_mbc::fullName("P 42/m b c");
const olxstr FastSG_P42_mbc::hallSymbol("-P 4c 2ab");
const olxstr FastSG_P42_mcm::fullName("P 42/m c m");
const olxstr FastSG_P42_mcm::hallSymbol("-P 4c 2c");
const olxstr FastSG_P42_mmc::fullName("P 42/m m c");
const olxstr FastSG_P42_mmc::hallSymbol("-P 4c 2");
const olxstr FastSG_P42_mnm::fullName("P 42/m n m");
const olxstr FastSG_P42_mnm::hallSymbol("-P 4n 2n");
const olxstr FastSG_P42_n::fullName("P 42/n");
const olxstr FastSG_P42_n::hallSymbol("-P 4bc");
const olxstr FastSG_P42_nbc::fullName("P 42/n b c");
const olxstr FastSG_P42_nbc::hallSymbol("-P 4ac 2b");
const olxstr FastSG_P42_ncm::fullName("P 42/n c m");
const olxstr FastSG_P42_ncm::hallSymbol("-P 4ac 2ac");
const olxstr FastSG_P42_nmc::fullName("P 42/n m c");
const olxstr FastSG_P42_nmc::hallSymbol("-P 4ac 2a");
const olxstr FastSG_P42_nnm::fullName("P 42/n n n");
const olxstr FastSG_P42_nnm::hallSymbol("-P 4ac 2bc");
const olxstr FastSG_P4212::fullName("P 42 1 2");
const olxstr FastSG_P4212::hallSymbol("P 4ab 2ab");
const olxstr FastSG_P422::fullName("P 4 2 2");
const olxstr FastSG_P422::hallSymbol("P 4 2");
const olxstr FastSG_P42212::fullName("P 42 21 2");
const olxstr FastSG_P42212::hallSymbol("P 4n 2n");
const olxstr FastSG_P4222::fullName("P 42 2 2");
const olxstr FastSG_P4222::hallSymbol("P 4c 2");
const olxstr FastSG_P4232::fullName("P 42 3 2");
const olxstr FastSG_P4232::hallSymbol("P 4n 2 3");
const olxstr FastSG_P42bc::fullName("P 42 b c");
const olxstr FastSG_P42bc::hallSymbol("P 4c -2ab");
const olxstr FastSG_P42cm::fullName("P 42 c m");
const olxstr FastSG_P42cm::hallSymbol("P 4c -2c");
const olxstr FastSG_P42mc::fullName("P 42 m c");
const olxstr FastSG_P42mc::hallSymbol("P 4c -2");
const olxstr FastSG_P42nm::fullName("P 42 n m");
const olxstr FastSG_P42nm::hallSymbol("P 4n -2n");
const olxstr FastSG_P43::fullName("P 43");
const olxstr FastSG_P43::hallSymbol("P 43");
const olxstr FastSG_P432::fullName("P 4 3 2");
const olxstr FastSG_P432::hallSymbol("P 4 2 3");
const olxstr FastSG_P43212::fullName("P 43 21 2");
const olxstr FastSG_P43212::hallSymbol("P 4nw 2abw");
const olxstr FastSG_P4322::fullName("P 43 2 2");
const olxstr FastSG_P4322::hallSymbol("P 43 2c");
const olxstr FastSG_P4332::fullName("P 43 3 2");
const olxstr FastSG_P4332::hallSymbol("P 4acd 2ab 3");
const olxstr FastSG_P4bm::fullName("P 4 b m");
const olxstr FastSG_P4bm::hallSymbol("P 4 -2ab");
const olxstr FastSG_P4cc::fullName("P 4 c c");
const olxstr FastSG_P4cc::hallSymbol("P 4 -2c");
const olxstr FastSG_P4mm::fullName("P 4 m m");
const olxstr FastSG_P4mm::hallSymbol("P 4 -2");
const olxstr FastSG_P4nc::fullName("P 4 n c");
const olxstr FastSG_P4nc::hallSymbol("P 4 -2n");
const olxstr FastSG_P6::fullName("P 6");
const olxstr FastSG_P6::hallSymbol("P 6");
const olxstr FastSG_P6_m::fullName("P 6/m");
const olxstr FastSG_P6_m::hallSymbol("-P 6");
const olxstr FastSG_P6_mcc::fullName("P 6/m c c");
const olxstr FastSG_P6_mcc::hallSymbol("-P 6 2c");
const olxstr FastSG_P6_mmm::fullName("P 6/m m m");
const olxstr FastSG_P6_mmm::hallSymbol("-P 6 2");
const olxstr FastSG_P61::fullName("P 61");
const olxstr FastSG_P61::hallSymbol("P 61");
const olxstr FastSG_P6122::fullName("P 61 2 2");
const olxstr FastSG_P6122::hallSymbol("P 61 2");
const olxstr FastSG_P62::fullName("P 62");
const olxstr FastSG_P62::hallSymbol("P 62");
const olxstr FastSG_P622::fullName("P 6 2 2");
const olxstr FastSG_P622::hallSymbol("P 6 2");
const olxstr FastSG_P6222::fullName("P 62 2 2");
const olxstr FastSG_P6222::hallSymbol("P 62 2");
const olxstr FastSG_P63::fullName("P 63");
const olxstr FastSG_P63::hallSymbol("P 6c");
const olxstr FastSG_P63_m::fullName("P 63/m");
const olxstr FastSG_P63_m::hallSymbol("-P 6c");
const olxstr FastSG_P63_mcm::fullName("P 63/m c m");
const olxstr FastSG_P63_mcm::hallSymbol("-P 6c 2");
const olxstr FastSG_P63_mmc::fullName("P 63/m m c");
const olxstr FastSG_P63_mmc::hallSymbol("-P 6c 2c");
const olxstr FastSG_P6322::fullName("P 63 2 2");
const olxstr FastSG_P6322::hallSymbol("P 6c 2c");
const olxstr FastSG_P63cm::fullName("P 63 c m");
const olxstr FastSG_P63cm::hallSymbol("P 6c -2");
const olxstr FastSG_P63mc::fullName("P 63 m c");
const olxstr FastSG_P63mc::hallSymbol("P 6c -2c");
const olxstr FastSG_P64::fullName("P 64");
const olxstr FastSG_P64::hallSymbol("P 64");
const olxstr FastSG_P6422::fullName("P 64 2 2");
const olxstr FastSG_P6422::hallSymbol("P 64 2");
const olxstr FastSG_P65::fullName("P 65");
const olxstr FastSG_P65::hallSymbol("P 65");
const olxstr FastSG_P6522::fullName("P 65 2 2");
const olxstr FastSG_P6522::hallSymbol("P 65 2");
const olxstr FastSG_P6cc::fullName("P 6 c c");
const olxstr FastSG_P6cc::hallSymbol("P 6 -2c");
const olxstr FastSG_P6mm::fullName("P 6 m m");
const olxstr FastSG_P6mm::hallSymbol("P 6 -2");
const olxstr FastSG_Pa::fullName("P 1 a 1");
const olxstr FastSG_Pa::hallSymbol("P -2ya");
const olxstr FastSG_Pa_3::fullName("P a -3");
const olxstr FastSG_Pa_3::hallSymbol("-P 2ac 2ab 3");
const olxstr FastSG_Pb11::fullName("P b 1 1");
const olxstr FastSG_Pb11::hallSymbol("P -2xb");
const olxstr FastSG_Pb21a::fullName("P b 21 a");
const olxstr FastSG_Pb21a::hallSymbol("P -2a -2ab");
const olxstr FastSG_Pb21m::fullName("P b 21 m");
const olxstr FastSG_Pb21m::hallSymbol("P -2 -2b");
const olxstr FastSG_Pb2b::fullName("P b 2 b");
const olxstr FastSG_Pb2b::hallSymbol("P -2b -2b");
const olxstr FastSG_Pb2n::fullName("P b 2 n");
const olxstr FastSG_Pb2n::hallSymbol("P -2ab -2ab");
const olxstr FastSG_Pba2::fullName("P b a 2");
const olxstr FastSG_Pba2::hallSymbol("P 2 -2ab");
const olxstr FastSG_Pbaa::fullName("P b a a");
const olxstr FastSG_Pbaa::hallSymbol("-P 2a 2b");
const olxstr FastSG_Pbab::fullName("P b a b");
const olxstr FastSG_Pbab::hallSymbol("-P 2b 2ab");
const olxstr FastSG_Pbam::fullName("P b a m");
const olxstr FastSG_Pbam::hallSymbol("-P 2 2ab");
const olxstr FastSG_Pban::fullName("P b a n");
const olxstr FastSG_Pban::hallSymbol("-P 2ab 2b");
const olxstr FastSG_Pbc21::fullName("P b c 21");
const olxstr FastSG_Pbc21::hallSymbol("P 2c -2b");
const olxstr FastSG_Pbca::fullName("P b c a");
const olxstr FastSG_Pbca::hallSymbol("-P 2ac 2ab");
const olxstr FastSG_Pbcb::fullName("P b c b");
const olxstr FastSG_Pbcb::hallSymbol("-P 2bc 2b");
const olxstr FastSG_Pbcm::fullName("P b c m");
const olxstr FastSG_Pbcm::hallSymbol("-P 2c 2b");
const olxstr FastSG_Pbcn::fullName("P b c n");
const olxstr FastSG_Pbcn::hallSymbol("-P 2n 2ab");
const olxstr FastSG_Pbm2::fullName("P b m 2");
const olxstr FastSG_Pbm2::hallSymbol("P 2 -2b");
const olxstr FastSG_Pbma::fullName("P b m a");
const olxstr FastSG_Pbma::hallSymbol("-P 2a 2ab");
const olxstr FastSG_Pbmb::fullName("P b m b");
const olxstr FastSG_Pbmb::hallSymbol("-P 2b 2b");
const olxstr FastSG_Pbmm::fullName("P b m m");
const olxstr FastSG_Pbmm::hallSymbol("-P 2 2b");
const olxstr FastSG_Pbmn::fullName("P b m n");
const olxstr FastSG_Pbmn::hallSymbol("-P 2ab 2ab");
const olxstr FastSG_Pbn21::fullName("P b n 21");
const olxstr FastSG_Pbn21::hallSymbol("P 2c -2ab");
const olxstr FastSG_Pbna::fullName("P b n a");
const olxstr FastSG_Pbna::hallSymbol("-P 2ac 2b");
const olxstr FastSG_Pbnb::fullName("P b n b");
const olxstr FastSG_Pbnb::hallSymbol("-P 2bc 2ab");
const olxstr FastSG_Pbnm::fullName("P b n m");
const olxstr FastSG_Pbnm::hallSymbol("-P 2c 2ab");
const olxstr FastSG_Pbnn::fullName("P b n n");
const olxstr FastSG_Pbnn::hallSymbol("-P 2n 2b");
const olxstr FastSG_Pc::fullName("P 1 c 1");
const olxstr FastSG_Pc::hallSymbol("P -2yc");
const olxstr FastSG_Pc11::fullName("P c 1 1");
const olxstr FastSG_Pc11::hallSymbol("P -2xc");
const olxstr FastSG_Pc21b::fullName("P c 21 b");
const olxstr FastSG_Pc21b::hallSymbol("P -2bc -2c");
const olxstr FastSG_Pc21n::fullName("P c 21 n");
const olxstr FastSG_Pc21n::hallSymbol("P -2n -2ac");
const olxstr FastSG_Pc2a::fullName("P c 2 a");
const olxstr FastSG_Pc2a::hallSymbol("P -2ac -2ac");
const olxstr FastSG_Pc2m::fullName("P c 2 m");
const olxstr FastSG_Pc2m::hallSymbol("P -2c -2c");
const olxstr FastSG_Pca21::fullName("P c a 21");
const olxstr FastSG_Pca21::hallSymbol("P 2c -2ac");
const olxstr FastSG_Pcaa::fullName("P c a a");
const olxstr FastSG_Pcaa::hallSymbol("-P 2ac 2c");
const olxstr FastSG_Pcab::fullName("P c a b");
const olxstr FastSG_Pcab::hallSymbol("-P 2bc 2ac");
const olxstr FastSG_Pcam::fullName("P c a m");
const olxstr FastSG_Pcam::hallSymbol("-P 2c 2ac");
const olxstr FastSG_Pcan::fullName("P c a n");
const olxstr FastSG_Pcan::hallSymbol("-P 2n 2c");
const olxstr FastSG_Pcc2::fullName("P c c 2");
const olxstr FastSG_Pcc2::hallSymbol("P 2 -2c");
const olxstr FastSG_Pcca::fullName("P c c a");
const olxstr FastSG_Pcca::hallSymbol("-P 2a 2ac");
const olxstr FastSG_Pccb::fullName("P c c b");
const olxstr FastSG_Pccb::hallSymbol("-P 2b 2c");
const olxstr FastSG_Pccm::fullName("P c c m");
const olxstr FastSG_Pccm::hallSymbol("-P 2 2c");
const olxstr FastSG_Pccn::fullName("P c c n");
const olxstr FastSG_Pccn::hallSymbol("-P 2ab 2ac");
const olxstr FastSG_Pcm21::fullName("P c m 21");
const olxstr FastSG_Pcm21::hallSymbol("P 2c -2c");
const olxstr FastSG_Pcma::fullName("P c m a");
const olxstr FastSG_Pcma::hallSymbol("-P 2ac 2ac");
const olxstr FastSG_Pcmb::fullName("P c m b");
const olxstr FastSG_Pcmb::hallSymbol("-P 2bc 2c");
const olxstr FastSG_Pcmm::fullName("P c m m");
const olxstr FastSG_Pcmm::hallSymbol("-P 2c 2c");
const olxstr FastSG_Pcmn::fullName("P c m n");
const olxstr FastSG_Pcmn::hallSymbol("-P 2n 2ac");
const olxstr FastSG_Pcn2::fullName("P c n 2");
const olxstr FastSG_Pcn2::hallSymbol("P 2 -2ac");
const olxstr FastSG_Pcna::fullName("P c n a");
const olxstr FastSG_Pcna::hallSymbol("-P 2a 2c");
const olxstr FastSG_Pcnb::fullName("P c n b");
const olxstr FastSG_Pcnb::hallSymbol("-P 2b 2ac");
const olxstr FastSG_Pcnm::fullName("P c n m");
const olxstr FastSG_Pcnm::hallSymbol("-P 2 2ac");
const olxstr FastSG_Pcnn::fullName("P c n n");
const olxstr FastSG_Pcnn::hallSymbol("-P 2ab 2c");
const olxstr FastSG_Pm::fullName("P 1 m 1");
const olxstr FastSG_Pm::hallSymbol("P -2y");
const olxstr FastSG_Pm_3::fullName("P m -3 -P");
const olxstr FastSG_Pm_3::hallSymbol("-P 2 2 3");
const olxstr FastSG_Pm_3m::fullName("P m -3 m");
const olxstr FastSG_Pm_3m::hallSymbol("-P 4 2 3");
const olxstr FastSG_Pm_3n::fullName("P m -3 n");
const olxstr FastSG_Pm_3n::hallSymbol("-P 4n 2 3");
const olxstr FastSG_Pm11::fullName("P m 1 1");
const olxstr FastSG_Pm11::hallSymbol("P -2x");
const olxstr FastSG_Pm21b::fullName("P m 21 b");
const olxstr FastSG_Pm21b::hallSymbol("P -2b -2");
const olxstr FastSG_Pm21n::fullName("P m 21 n");
const olxstr FastSG_Pm21n::hallSymbol("P -2ab -2");
const olxstr FastSG_Pm2a::fullName("P m 2 a");
const olxstr FastSG_Pm2a::hallSymbol("P -2a -2a");
const olxstr FastSG_Pm2m::fullName("P m 2 m");
const olxstr FastSG_Pm2m::hallSymbol("P -2 -2");
const olxstr FastSG_Pma2::fullName("P m a 2");
const olxstr FastSG_Pma2::hallSymbol("P 2 -2a");
const olxstr FastSG_Pmaa::fullName("P m a a");
const olxstr FastSG_Pmaa::hallSymbol("-P 2a 2");
const olxstr FastSG_Pmab::fullName("P m a b");
const olxstr FastSG_Pmab::hallSymbol("-P 2b 2a");
const olxstr FastSG_Pmam::fullName("P m a m");
const olxstr FastSG_Pmam::hallSymbol("-P 2 2a");
const olxstr FastSG_Pman::fullName("P m a n");
const olxstr FastSG_Pman::hallSymbol("-P 2ab 2");
const olxstr FastSG_Pmc21::fullName("P m c 21");
const olxstr FastSG_Pmc21::hallSymbol("P 2c -2");
const olxstr FastSG_Pmca::fullName("P m c a");
const olxstr FastSG_Pmca::hallSymbol("-P 2ac 2a");
const olxstr FastSG_Pmcb::fullName("P m c b");
const olxstr FastSG_Pmcb::hallSymbol("-P 2bc 2");
const olxstr FastSG_Pmcm::fullName("P m c m");
const olxstr FastSG_Pmcm::hallSymbol("-P 2c 2");
const olxstr FastSG_Pmcn::fullName("P m c n");
const olxstr FastSG_Pmcn::hallSymbol("-P 2n 2a");
const olxstr FastSG_Pmm2::fullName("P m m 2");
const olxstr FastSG_Pmm2::hallSymbol("P 2 -2");
const olxstr FastSG_Pmma::fullName("P m m a");
const olxstr FastSG_Pmma::hallSymbol("-P 2a 2a");
const olxstr FastSG_Pmmb::fullName("P m m b");
const olxstr FastSG_Pmmb::hallSymbol("-P 2b 2");
const olxstr FastSG_Pmmm::fullName("P m m m");
const olxstr FastSG_Pmmm::hallSymbol("-P 2 2");
const olxstr FastSG_Pmmn::fullName("P m m n");
const olxstr FastSG_Pmmn::hallSymbol("-P 2ab 2a");
const olxstr FastSG_Pmn21::fullName("P m n 21");
const olxstr FastSG_Pmn21::hallSymbol("P 2ac -2");
const olxstr FastSG_Pmna::fullName("P m n a");
const olxstr FastSG_Pmna::hallSymbol("-P 2ac 2");
const olxstr FastSG_Pmnb::fullName("P m n b");
const olxstr FastSG_Pmnb::hallSymbol("-P 2bc 2a");
const olxstr FastSG_Pmnm::fullName("P m n m");
const olxstr FastSG_Pmnm::hallSymbol("-P 2c 2a");
const olxstr FastSG_Pmnn::fullName("P m n n");
const olxstr FastSG_Pmnn::hallSymbol("-P 2n 2");
const olxstr FastSG_Pn::fullName("P 1 n 1");
const olxstr FastSG_Pn::hallSymbol("P -2yac");
const olxstr FastSG_Pn_3::fullName("P n -3");
const olxstr FastSG_Pn_3::hallSymbol("-P 2ab 2bc 3");
const olxstr FastSG_Pn_3m::fullName("P n -3 m");
const olxstr FastSG_Pn_3m::hallSymbol("-P 4bc 2bc 3");
const olxstr FastSG_Pn_3n::fullName("P n -3 n");
const olxstr FastSG_Pn_3n::hallSymbol("-P 4a 2bc 3");
const olxstr FastSG_Pn11::fullName("P n 1 1");
const olxstr FastSG_Pn11::hallSymbol("P -2xbc");
const olxstr FastSG_Pn21a::fullName("P n 21 a");
const olxstr FastSG_Pn21a::hallSymbol("P -2ac -2n");
const olxstr FastSG_Pn21m::fullName("P n 21 m");
const olxstr FastSG_Pn21m::hallSymbol("P -2 -2bc");
const olxstr FastSG_Pn2b::fullName("P n 2 b");
const olxstr FastSG_Pn2b::hallSymbol("P -2bc -2bc");
const olxstr FastSG_Pn2n::fullName("P n 2 n");
const olxstr FastSG_Pn2n::hallSymbol("P -2n -2n");
const olxstr FastSG_Pna21::fullName("P n a 21");
const olxstr FastSG_Pna21::hallSymbol("P 2c -2n");
const olxstr FastSG_Pnaa::fullName("P n a a");
const olxstr FastSG_Pnaa::hallSymbol("-P 2ac 2bc");
const olxstr FastSG_Pnab::fullName("P n a b");
const olxstr FastSG_Pnab::hallSymbol("-P 2bc 2n");
const olxstr FastSG_Pnam::fullName("P n a m");
const olxstr FastSG_Pnam::hallSymbol("-P 2c 2n");
const olxstr FastSG_Pnan::fullName("P n a n");
const olxstr FastSG_Pnan::hallSymbol("-P 2n 2bc");
const olxstr FastSG_Pnc2::fullName("P n c 2");
const olxstr FastSG_Pnc2::hallSymbol("P 2 -2bc");
const olxstr FastSG_Pnca::fullName("P n c a");
const olxstr FastSG_Pnca::hallSymbol("-P 2a 2n");
const olxstr FastSG_Pncb::fullName("P n c b");
const olxstr FastSG_Pncb::hallSymbol("-P 2b 2bc");
const olxstr FastSG_Pncm::fullName("P n c m");
const olxstr FastSG_Pncm::hallSymbol("-P 2 2bc");
const olxstr FastSG_Pncn::fullName("P n c n");
const olxstr FastSG_Pncn::hallSymbol("-P 2ab 2n");
const olxstr FastSG_Pnm21::fullName("P n m 21");
const olxstr FastSG_Pnm21::hallSymbol("P 2bc -2bc");
const olxstr FastSG_Pnma::fullName("P n m a");
const olxstr FastSG_Pnma::hallSymbol("-P 2ac 2n");
const olxstr FastSG_Pnmb::fullName("P n m b");
const olxstr FastSG_Pnmb::hallSymbol("-P 2bc 2bc");
const olxstr FastSG_Pnmm::fullName("P n m m");
const olxstr FastSG_Pnmm::hallSymbol("-P 2c 2bc");
const olxstr FastSG_Pnmn::fullName("P n m n");
const olxstr FastSG_Pnmn::hallSymbol("-P 2n 2n");
const olxstr FastSG_Pnn2::fullName("P n n 2");
const olxstr FastSG_Pnn2::hallSymbol("P 2 -2n");
const olxstr FastSG_Pnna::fullName("P n n a");
const olxstr FastSG_Pnna::hallSymbol("-P 2a 2bc");
const olxstr FastSG_Pnnb::fullName("P n n b");
const olxstr FastSG_Pnnb::hallSymbol("-P 2b 2n");
const olxstr FastSG_Pnnm::fullName("P n n m");
const olxstr FastSG_Pnnm::hallSymbol("-P 2 2n");
const olxstr FastSG_Pnnn::fullName("P n n n");
const olxstr FastSG_Pnnn::hallSymbol("-P 2ab 2bc");
const olxstr FastSG_R_3::fullName("R -3");
const olxstr FastSG_R_3::hallSymbol("-R 3");
const olxstr FastSG_R_3_r::fullName("R -3");
const olxstr FastSG_R_3_r::hallSymbol("-P 3*");
const olxstr FastSG_R_3c::fullName("R -3 c");
const olxstr FastSG_R_3c::hallSymbol("-R 3 2\"c");
const olxstr FastSG_R_3c_r::fullName("R -3 c");
const olxstr FastSG_R_3c_r::hallSymbol("-P 3* 2n");
const olxstr FastSG_R_3m::fullName("R -3 m");
const olxstr FastSG_R_3m::hallSymbol("-R 3 2\"");
const olxstr FastSG_R_3m_r::fullName("R -3 m");
const olxstr FastSG_R_3m_r::hallSymbol("-P 3* 2");
const olxstr FastSG_R3::fullName("R 3");
const olxstr FastSG_R3::hallSymbol("R 3");
const olxstr FastSG_R32::fullName("R 32");
const olxstr FastSG_R32::hallSymbol("R 3 2\"");
const olxstr FastSG_R32_r::fullName("R 32");
const olxstr FastSG_R32_r::hallSymbol("P 3* 2");
const olxstr FastSG_R3_r::fullName("R 3");
const olxstr FastSG_R3_r::hallSymbol("P 3*");
const olxstr FastSG_R3c::fullName("R 3 c");
const olxstr FastSG_R3c::hallSymbol("R 3 -2\"c");
const olxstr FastSG_R3c_r::fullName("R 3 c");
const olxstr FastSG_R3c_r::hallSymbol("P 3* -2n");
const olxstr FastSG_R3m::fullName("R 3 m");
const olxstr FastSG_R3m::hallSymbol("R 3 -2\"");
const olxstr FastSG_R3m_r::fullName("R 3 m");
const olxstr FastSG_R3m_r::hallSymbol("P 3* -2");
