#!/bin/bash

echo "This installer will install premade binaries onto your system";
if test -d $HOME/olex;
	then echo 'The olex directory is already present';
	echo 'Overwriting binaries only';
	cp ./bin/* $HOME/olex/;
else
        echo "Creating olex directory";
	mkdir $HOME/olex;
	echo "Copying binaries";
	cp ./bin/* $HOME/olex/;
	echo "Creating scripts and icons";
	cp ./scripts/usettings.dat $HOME/olex/;
	cp ./scripts/startup $HOME/olex/;
# experimental put startup script into bin so olex2 can be called from anywhere
        if test -d $HOME/bin; 
                then cp ./scripts/startup $HOME/bin/olex2; 
        else 
                mkdir $HOME/bin;
                cp ./scripts/startup $HOME/bin/olex2;
        fi;
        cp ./scripts/olex2.xpm $HOME/olex/;
        cp ./scripts/olex2.desktop $HOME/Desktop/;
# use sed to alter startup path for different install dir
        sed -i "s|PROXY|$PROXY|g" $HOME/olex/usettings.dat;
        sed -i "s|OLEX2BINPATH|$HOME/bin/olex2|g" $HOME/Desktop/olex2.desktop;
        sed -i "s|OLEX2PATH|$HOME/olex|g" $HOME/Desktop/olex2.desktop;
        sed -i "s|OLEX_INS|$HOME/olex|g" $HOME/bin/olex2;
        sed -i "s|OLEX_BIN|$HOME/bin|g" $HOME/bin/olex2;
        chmod +x $HOME/olex/startup $HOME/bin/olex2;
        echo "Installed"
        echo "Downloading and Updating GUI"
        $HOME/olex/unirun $HOME/olex/
        echo '*****************************************************'
        echo 'Done, double click on olex2 icon on your desktop or'
        echo 'call olex2 from console'
fi;

